springdoc:
  api-docs:
    groups:
      enabled: true
  # 分组配置
  group-configs:
    - group: 核销(write-off)
      paths-to-match: [ /api/v1/write-off/** ]
  swagger-ui:
    disable-swagger-default-url: true

#mybatis-plus
mybatis-plus:
  type-aliases-package: com.example.demo.domain
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启SQL日志，观察是否真是批量
    default-executor-type: batch # 尝试设置为BATCH执行器
  global-config:
    db-config:
      # 全局统一下雪花算法主键
      id-type: assign_id
spring:
  profiles:
    active: dev
  rabbitmq:
    listener:
      simple:
        # 强制开启手动确认模式，阻止Spring重复ACK
        acknowledge-mode: manual
        concurrency: 100
        max-concurrency: 150
        prefetch: 200